AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - spec/**/*
    - config/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*
    - app/controllers/bets_controller.rb
    - lib/bet_params.rb
    - app/controllers/accounts_controller.rb
    - lib/maximum_bet.rb

Metrics/LineLength:
  Exclude:
    - config/initializers/*
    - db/**/*

Metrics/MethodLength:
  Max: 10
  Exclude:
    - app/models/ability.rb
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/**/*
    - Guardfile
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/**/*

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - db/seeds.rb

Layout/AlignHash:
  Exclude:
    - lib/bet_params.rb
